//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int AgreementId { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> Contact { get; set; }
        public Nullable<int> AgreementTypeId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string Article { get; set; }
        public string Text { get; set; }
        public Nullable<int> NumberOfMonths { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> InvoicedToDate { get; set; }
    }
}
