//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_MenuItem
    {
        public int ObjectID { get; set; }
        public int AssociationID { get; set; }
        public int ArticleID { get; set; }
        public int MainID { get; set; }
        public int MenuItemID { get; set; }
        public System.DateTime Modified { get; set; }
        public int Priority { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
