//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Banner
    {
        public int ObjectId { get; set; }
        public int ArticleId { get; set; }
        public int BannerId { get; set; }
        public int AssociationId { get; set; }
        public int Priority { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Banner Banner { get; set; }
        public virtual Article Article { get; set; }
    }
}
