//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.Article1 = new HashSet<Article>();
            this.Article_Banner = new HashSet<Article_Banner>();
            this.Article_MenuItem = new HashSet<Article_MenuItem>();
            this.Article_MenuItem1 = new HashSet<Article_MenuItem>();
        }
    
        public int ArticleID { get; set; }
        public Nullable<int> MainID { get; set; }
        public short Version { get; set; }
        public short Status { get; set; }
        public short PublishStatus { get; set; }
        public int PersonID { get; set; }
        public string Headline { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ShowDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Abstract { get; set; }
        public string Fullstory { get; set; }
        public string TOC { get; set; }
        public int Priority { get; set; }
        public string Author { get; set; }
        public bool Discuss { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string meta_description { get; set; }
        public string meta_keywords { get; set; }
        public bool LockStatus { get; set; }
        public Nullable<System.DateTime> LockTime { get; set; }
        public Nullable<int> LockedBy { get; set; }
        public Nullable<int> DataObjectID { get; set; }
        public Nullable<int> DataObjectRecordID { get; set; }
        public System.DateTime Modified { get; set; }
        public string Alias { get; set; }
        public string CompleteArticle { get; set; }
        public string PictureDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Article1 { get; set; }
        public virtual Article Article2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Banner> Article_Banner { get; set; }
        public virtual PictureProperty PictureProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_MenuItem> Article_MenuItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_MenuItem> Article_MenuItem1 { get; set; }
    }
}
