//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Banner()
        {
            this.Article_Banner = new HashSet<Article_Banner>();
        }
    
        public int BannerId { get; set; }
        public string BannerName { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime ShowDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public short Status { get; set; }
        public int Impressions { get; set; }
        public Nullable<int> MaxImpressions { get; set; }
        public int Clicks { get; set; }
        public Nullable<int> MaxClicks { get; set; }
        public Nullable<int> DestinationLinkId { get; set; }
        public byte ContentType { get; set; }
        public Nullable<int> PictureId { get; set; }
        public Nullable<int> PictureLinkId { get; set; }
        public string HtmlText { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public short FlashVersion { get; set; }
        public Nullable<int> DataObjectId { get; set; }
        public Nullable<int> DataObjectRecordId { get; set; }
        public string MetaKeywords { get; set; }
        public int PersonId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Banner> Article_Banner { get; set; }
        public virtual PictureProperty PictureProperty { get; set; }
        public virtual Person Person { get; set; }
    }
}
