//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingPriceDetail
    {
        public int Id { get; set; }
        public bool IsInternal { get; set; }
        public string Article1 { get; set; }
        public string Article2 { get; set; }
        public int UnitId { get; set; }
        public string UnitDesc { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public decimal Price { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
