//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookingDetail()
        {
            this.BookingServiceLists = new HashSet<BookingServiceList>();
        }
    
        public int BookingID { get; set; }
        public string BookingType { get; set; }
        public int ServiceID { get; set; }
        public int UserID { get; set; }
        public string BookingName { get; set; }
        public Nullable<int> NoOfPeople { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsFoodOrder { get; set; }
        public Nullable<int> Status { get; set; }
        public int BuildingID { get; set; }
        public int ServiceType { get; set; }
        public int SendMessageType { get; set; }
        public string UnitText { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<double> NetAmount { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> MainBookingId { get; set; }
        public Nullable<System.DateTime> FollowUpDate { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<int> Ordering { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsDeliver { get; set; }
        public Nullable<bool> IsClean { get; set; }
        public bool IsInternal { get; set; }
        public string InvoMessage { get; set; }
        public bool IsMVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingServiceList> BookingServiceLists { get; set; }
    }
}
