//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMessage
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> BookingID { get; set; }
        public string To { get; set; }
        public string Body { get; set; }
        public string Attachments { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string Subject { get; set; }
    }
}
