//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataObjectPage
    {
        public int PageID { get; set; }
        public int DataObjectID { get; set; }
        public int PageNumber { get; set; }
        public string TopText { get; set; }
        public string BottomText { get; set; }
        public string PageHTML { get; set; }
        public string FilteredHTML { get; set; }
        public string PageXML { get; set; }
        public System.DateTime Modified { get; set; }
        public string PageHiddenHTML { get; set; }
    }
}
