//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuItem()
        {
            this.MenuItem1 = new HashSet<MenuItem>();
            this.Article_MenuItem = new HashSet<Article_MenuItem>();
        }
    
        public int MenuItemID { get; set; }
        public string MenuItemName { get; set; }
        public Nullable<int> Parentid { get; set; }
        public byte Status { get; set; }
        public int Priority { get; set; }
        public string Title { get; set; }
        public short Protected { get; set; }
        public int TemplateID { get; set; }
        public byte Type { get; set; }
        public System.DateTime Showdate { get; set; }
        public Nullable<System.DateTime> Expiredate { get; set; }
        public string URL { get; set; }
        public string Target { get; set; }
        public Nullable<int> Pictureid { get; set; }
        public string Sortorder { get; set; }
        public Nullable<int> DataObjectID { get; set; }
        public Nullable<int> DataObjectRecordID { get; set; }
        public Nullable<int> Lvl { get; set; }
        public string hierarchy { get; set; }
        public System.DateTime Modified { get; set; }
        public string Fullpath { get; set; }
        public string MetaKey { get; set; }
        public string MetaDescription { get; set; }
        public string Alias { get; set; }
        public string TypeHierarchy { get; set; }
        public string AliasHierarchy { get; set; }
        public Nullable<int> LCID { get; set; }
        public short RSSEnabled { get; set; }
        public Nullable<int> RSSMaxNoOfArticles { get; set; }
        public Nullable<int> ArticleTemplateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuItem> MenuItem1 { get; set; }
        public virtual MenuItem MenuItem2 { get; set; }
        public virtual PictureProperty PictureProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_MenuItem> Article_MenuItem { get; set; }
    }
}
