//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderhead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orderhead()
        {
            this.Orderlines = new HashSet<Orderline>();
        }
    
        public int OrderNo { get; set; }
        public System.DateTime Orderdate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerNo { get; set; }
        public string OurReference { get; set; }
        public string YourReference { get; set; }
        public string EmailAddress { get; set; }
        public int VAT { get; set; }
        public string Ordertype { get; set; }
        public string ERPClient { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDeliver { get; set; }
        public Nullable<bool> IsClean { get; set; }
        public Nullable<int> NoOFPeople { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<int> bookingId { get; set; }
        public Nullable<int> VismaOrderNo { get; set; }
        public Nullable<System.DateTime> VismaOrderDate { get; set; }
        public Nullable<bool> ISVismaOrder { get; set; }
        public Nullable<bool> IsOrderConfirm { get; set; }
        public string VMOrderFailedErrorMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orderline> Orderlines { get; set; }
    }
}
