//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orderline
    {
        public int ID { get; set; }
        public int FoodID { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public int BookingID { get; set; }
        public bool Status { get; set; }
        public string ArticleId { get; set; }
        public string Tekst { get; set; }
        public Nullable<decimal> Sum { get; set; }
        public Nullable<bool> IsKitchen { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<double> VATPercent { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UnitText { get; set; }
        public Nullable<bool> IsVat { get; set; }
        public Nullable<bool> IsMainService { get; set; }
        public int OrderHeadId { get; set; }
        public string ServiceName { get; set; }
        public string Time { get; set; }
        public decimal CostPrice { get; set; }
        public decimal CostTotal { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual Orderhead Orderhead { get; set; }
    }
}
