//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationUnit()
        {
            this.OrganizationUnit_Person = new HashSet<OrganizationUnit_Person>();
        }
    
        public int OrganizationUnitID { get; set; }
        public string OrganizationUnitName { get; set; }
        public byte Type { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string Url { get; set; }
        public string Code { get; set; }
        public string OrgNumber { get; set; }
        public string RefNumber { get; set; }
        public string Telephone { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public Nullable<byte> Branch { get; set; }
        public int Priority { get; set; }
        public string Comment { get; set; }
        public string LongDescription { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Lvl { get; set; }
        public string Hierarchy { get; set; }
        public string FullPath { get; set; }
        public byte Status { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public string Homepage { get; set; }
        public string ExternalID { get; set; }
        public string WorkingHoursStart { get; set; }
        public string WorkingHoursEnd { get; set; }
        public System.DateTime Modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationUnit_Person> OrganizationUnit_Person { get; set; }
        public virtual PictureProperty PictureProperty { get; set; }
    }
}
