//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingService.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.OrganizationUnit_Person = new HashSet<OrganizationUnit_Person>();
            this.PictureProperties = new HashSet<PictureProperty>();
            this.Banners = new HashSet<Banner>();
        }
    
        public int PersonID { get; set; }
        public string GivenName { get; set; }
        public string FamilyName { get; set; }
        public string AdditionalNames { get; set; }
        public string NamePrefix { get; set; }
        public string NameSuffix { get; set; }
        public string NickName { get; set; }
        public string DisplayName { get; set; }
        public string LoginName { get; set; }
        public string Title { get; set; }
        public string OfficeFunction { get; set; }
        public Nullable<int> PictureID { get; set; }
        public string EmployeeNo { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public bool CanReceiveHTMLMail { get; set; }
        public string IMAddress { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Email3 { get; set; }
        public string Url { get; set; }
        public string Fax { get; set; }
        public string SMSNumber { get; set; }
        public string WorkPhone { get; set; }
        public string Telephone2 { get; set; }
        public string Telephone3 { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string MartialStatus { get; set; }
        public string PartnerName { get; set; }
        public Nullable<System.DateTime> PartnersBirthdate { get; set; }
        public string Comment { get; set; }
        public string Motto { get; set; }
        public string Education { get; set; }
        public Nullable<decimal> TimeZone { get; set; }
        public string Course { get; set; }
        public string Expertise { get; set; }
        public string Certification { get; set; }
        public string LongDescription { get; set; }
        public byte Status { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public string Custom1 { get; set; }
        public string Custom2 { get; set; }
        public string Custom3 { get; set; }
        public bool RTL { get; set; }
        public string Culture { get; set; }
        public string UICulture { get; set; }
        public string WorkingHoursStart { get; set; }
        public string WorkingHoursEnd { get; set; }
        public string ExternalID { get; set; }
        public Nullable<System.DateTime> PasswordExpiryDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> Theme { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> PlatformType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationUnit_Person> OrganizationUnit_Person { get; set; }
        public virtual PictureProperty PictureProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PictureProperty> PictureProperties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners { get; set; }
    }
}
